-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS bdc.livro
(
    isbn numeric(13, 0) NOT NULL,
    titulo character varying(40) NOT NULL,
    valor numeric(6, 2),
    autor character varying(30) NOT NULL,
    autor_2 character varying(30) NOT NULL,
    PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS bdc.venda
(
    codigo numeric(6, 0) NOT NULL,
    quantidade numeric(4, 0) NOT NULL,
    valor numeric(6, 2) NOT NULL,
    livro_fk numeric(13, 0) NOT NULL,
    PRIMARY KEY (codigo)
);

ALTER TABLE IF EXISTS bdc.venda
    ADD CONSTRAINT venda_livro_fk FOREIGN KEY (livro_fk)
    REFERENCES bdc.livro (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;